version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: IderzpBCKrMJJSAAkJXzdGfiVmGAjtBm
      MYSQL_DATABASE: ticketTrip
      MYSQL_USER: root
      MYSQL_PASSWORD: IderzpBCKrMJJSAAkJXzdGfiVmGAjtBm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  your_app:
    image: your-app-image
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://root:IderzpBCKrMJJSAAkJXzdGfiVmGAjtBm@viaduct.proxy.rlwy.net:56177/ticketTrip
      DB_USERNAME: root
      DB_PASSWORD: IderzpBCKrMJJSAAkJXzdGfiVmGAjtBm
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:

